// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SecretFormController from "./secret_form_controller"
application.register("secret-form", SecretFormController)
import SecretRetrievalController from "./secret_retrieval_controller"
application.register("secret-retrieval", SecretRetrievalController)
